<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="337" started-at="2019-08-14T11:15:44Z" finished-at="2019-08-14T11:15:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="337" started-at="2019-08-14T11:15:44Z" finished-at="2019-08-14T11:15:45Z">
      <class name="com.byndr.testcases.LoginTest">
        <test-method status="FAIL" signature="init()[pri:0, instance:com.byndr.testcases.LoginTest@16c0663d]" name="init" is-config="true" duration-ms="0" started-at="2019-08-14T16:45:44Z" finished-at="2019-08-14T16:45:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.byndr.TestBase.openApplicationInBrowser(TestBase.java:77)
	at com.byndr.TestBase.<init>(TestBase.java:61)
	at com.byndr.TestBase.getTestBaseInstance(TestBase.java:40)
	at com.byndr.testcases.LoginTest.init(LoginTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="SKIP" signature="byndrTitleTest()[pri:0, instance:com.byndr.testcases.LoginTest@16c0663d]" name="byndrTitleTest" duration-ms="5" started-at="2019-08-14T16:45:45Z" finished-at="2019-08-14T16:45:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- byndrTitleTest -->
        <test-method status="SKIP" signature="loginTest()[pri:0, instance:com.byndr.testcases.LoginTest@16c0663d]" name="loginTest" duration-ms="1" started-at="2019-08-14T16:45:45Z" finished-at="2019-08-14T16:45:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.byndr.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
